kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "rating-bot.fullname" . }}
  labels:
    helm.sh/chart: {{ include "rating-bot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.diskSize }}
